pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

dependencyResolutionManagement {
    repositories {
        maven {
            name = "Wisp Forest"
            url = "https://maven.wispforest.io/releases/"
        }
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        mavenCentral()
        maven {
            name = "JitPack"
            url = "https://jitpack.io"
        }
    }
}
// Should match your modid
rootProject.name = 'puppyutils'
