package de.puppyutils.client.utils;

import java.io.IOException;
import com.mojang.brigadier.arguments.IntegerArgumentType;
import de.puppyutils.client.routing.MacroManager;
import de.puppyutils.client.routing.WaypointRenderer;
import net.minecraft.core.BlockPos;
import com.mojang.brigadier.context.CommandContext;
import net.fabricmc.fabric.api.client.command.v2.ClientCommandRegistrationCallback;
import net.fabricmc.fabric.api.client.command.v2.ClientCommands;
import net.fabricmc.fabric.api.client.command.v2.FabricClientCommandSource;

public class CommandHandler {
    public static void register() {
        ClientCommandRegistrationCallback.EVENT.register((dispatcher, registryAccess) -> {
            dispatcher.register(
                ClientCommands.literal("togglewp")
                    .then(ClientCommands.argument("x", IntegerArgumentType.integer())
                        .then(ClientCommands.argument("y", IntegerArgumentType.integer())
                            .then(ClientCommands.argument("z", IntegerArgumentType.integer())
                                .executes(context -> toggleWaypoint(context))))));
        });
        ClientCommandRegistrationCallback.EVENT.register((dispatcher, registryAccess) -> {
            dispatcher.register(
                ClientCommands.literal("testfeature_macro")
                    .executes(context -> testMacro()));
        });
    }

    private static int toggleWaypoint(CommandContext<FabricClientCommandSource> context) {
        int x = IntegerArgumentType.getInteger(context, "x");
        int y = IntegerArgumentType.getInteger(context, "y");
        int z = IntegerArgumentType.getInteger(context, "z");
        BlockPos pos = new BlockPos(x, y, z);
        //WaypointRenderer.toggleHighlightedBlock(pos);
        return 1;
    }

    private static int testMacro(){
        MacroManager macros = new MacroManager();
        macros.addWalkAction(new BlockPos(130, 64, -40));
        macros.addWalkAction(new BlockPos(125, 64, -40));
        macros.addWalkAction(new BlockPos(120, 64, -40));
        try {
            macros.saveMacro("autogenerated_test_route");
        } catch (IOException e) {
            //TODO: Auto-generated catch block
            e.printStackTrace();
        }
        return 1;
    }
}
